name: Project Board Automation

on:
  issues:
    types: [opened, assigned, closed, reopened]

jobs:
  automate_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move new issues to "To Do"
        if: github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "Major Project: Guard Dog"
          column: "To Do"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move assigned issues to "In Progress"
        if: github.event.action == 'assigned'
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "Major Project: Guard Dog"
          column: "In Progress"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move closed issues to "Done"
        if: github.event.action == 'closed'
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "Major Project: Guard Dog"
          column: "Done"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reopen issues â†’ To Do
        if: github.event.action == 'reopened'
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "Major Project: Guard Dog"
          column: "To Do"
          repo-token: ${{ secrets.GITHUB_TOKEN }}


